2018-10-05 11:12:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DATABASECHANGELOGLOCK" not found; SQL statement:
select count(*) from PUBLIC.DATABASECHANGELOGLOCK [42102-197]
2018-10-08 15:01:22 jdbc[65]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:699)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:685)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2018-10-15 15:16:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER_AUTO" not found; SQL statement:
select user_auto0_.id as id1_7_, user_auto0_.giorno as giorno2_7_, user_auto0_.oggetto as oggetto3_7_ from user_auto user_auto0_ order by user_auto0_.id asc limit ? [42102-197]
2018-10-15 15:58:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER_AUTO" not found; SQL statement:
select user_auto0_.id as id1_7_, user_auto0_.giorno as giorno2_7_, user_auto0_.oggetto as oggetto3_7_ from user_auto user_auto0_ order by user_auto0_.id asc limit ? [42102-197]
2018-10-15 15:58:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER_AUTO" not found; SQL statement:
select user_auto0_.id as id1_7_, user_auto0_.giorno as giorno2_7_, user_auto0_.oggetto as oggetto3_7_ from user_auto user_auto0_ order by user_auto0_.id asc limit ? [42102-197]
2018-10-15 16:03:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER_AUTO" not found; SQL statement:
select user_auto0_.id as id1_7_ from user_auto user_auto0_ order by user_auto0_.id asc limit ? [42102-197]
2018-10-15 16:03:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER_AUTO" not found; SQL statement:
select user_auto0_.id as id1_7_ from user_auto user_auto0_ order by user_auto0_.id asc limit ? [42102-197]
2018-10-18 13:04:43 jdbc[43]: exception
org.h2.jdbc.JdbcSQLException: Table "USER_AUTO" not found; SQL statement:
select user_auto0_.id as id1_7_ from user_auto user_auto0_ order by user_auto0_.id asc limit ? [42102-197]
